# A string used as a project reference and to name resources based on the project.
project_id = "zjmkdmmnajzevoupgfhg"

[api]
# Port for the API
port = 54321
# Schemas to expose in the API
schemas = []
# Extra schemas to add to the API
extra_schemas = ["public", "storage", "graphql_public"]

[db]
# Port for the database
port = 54322
# The database major version
major_version = 15

[realtime]
enabled = true

[studio]
# Port for the Studio
port = 54323

# Email testing
[inbucket]
# Port for the SMTP server
smtp_port = 54324
# Port for the POP3 API
pop3_port = 54325
# Port for the web interface
web_port = 54326

[storage]
# The storage backend to use
backend = "file"
# The path to the storage data
file_storage_backend_path = "./storage"

[auth]
# The host of the JWT issuer
host = "localhost"
# The port of the JWT issuer
port = 9999

[auth.smtp]
# SMTP configuration for auth emails
host = "localhost"
port = 54324

[functions.grow-webhook]
verify_jwt = false

[functions.grow-payment]
verify_jwt = true

[functions.facebook-leads]
verify_jwt = true
